//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunForrest.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunForrest.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string AbortScriptButton {
            get {
                return ResourceManager.GetString("AbortScriptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddScriptButton {
            get {
                return ResourceManager.GetString("AddScriptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Var.
        /// </summary>
        public static string AddVariableButton {
            get {
                return ResourceManager.GetString("AddVariableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteVariableButton {
            get {
                return ResourceManager.GetString("DeleteVariableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG.
        /// </summary>
        public static string LogButton {
            get {
                return ResourceManager.GetString("LogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewScriptsButton {
            get {
                return ResourceManager.GetString("NewScriptsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenScriptsFileButton {
            get {
                return ResourceManager.GetString("OpenScriptsFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string RecentScriptsButton {
            get {
                return ResourceManager.GetString("RecentScriptsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveScriptButton {
            get {
                return ResourceManager.GetString("RemoveScriptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run, Forrest, run!.
        /// </summary>
        public static string RunScriptsButton {
            get {
                return ResourceManager.GetString("RunScriptsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveScriptsFileButton {
            get {
                return ResourceManager.GetString("SaveScriptsFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveVariablesButtonName {
            get {
                return ResourceManager.GetString("SaveVariablesButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCR.
        /// </summary>
        public static string ScriptButton {
            get {
                return ResourceManager.GetString("ScriptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ScriptDataViewCloseButton {
            get {
                return ResourceManager.GetString("ScriptDataViewCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string ShowHideOutputButton {
            get {
                return ResourceManager.GetString("ShowHideOutputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop, Forrest, stop!.
        /// </summary>
        public static string StopScriptsButton {
            get {
                return ResourceManager.GetString("StopScriptsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAR.
        /// </summary>
        public static string VariablesButton {
            get {
                return ResourceManager.GetString("VariablesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved: {0}.
        /// </summary>
        public static string VariablesSavedMessageFormat {
            get {
                return ResourceManager.GetString("VariablesSavedMessageFormat", resourceCulture);
            }
        }
    }
}
